Repository aurora-is-near/aurora-workspace, pull requests merged in 2023-05, with the labels that each got.

#21 Feat: Extend `EthConnector` contract for custom user
  Cargo.lock
  workspace-eth-connector/src/contract.rs
  workspace-eth-connector/tests/fungible_token_tests.rs
  workspace-utils/src/lib.rs
Labels: enhancement

#22 Feat: extend `eth-connector` utility
  Cargo.lock
  res/mock_eth_connector/src/connector.rs
  res/mock_eth_connector/src/lib.rs
  workspace-eth-connector/Cargo.toml
  workspace-eth-connector/src/contract.rs
  workspace-eth-connector/src/operation.rs
  workspace-eth-connector/src/types.rs
  workspace-eth-connector/tests/fungible_token_tests.rs
Labels: refactoring, enhancement, do-not-merge

#25 Feat: rename `get_access_right` to `get_account_with_access_right`
  res/mock_eth_connector/src/admin_controlled.rs
  res/mock_eth_connector/src/lib.rs
  workspace-eth-connector/src/contract.rs
  workspace-eth-connector/src/operation.rs
  workspace-eth-connector/tests/fungible_token_tests.rs
Labels: enhancement, eth-connectot

#26 Feat: remove `statistics_aurora_accounts_counter`
  res/mock_eth_connector/src/migration.rs
  workspace-eth-connector/src/types.rs
Labels: enhancement

#27 chore: remove get_accounts_counter method from eth-connector
  res/mock_eth_connector/src/connector.rs
  res/mock_eth_connector/src/lib.rs
  workspace-eth-connector/src/contract.rs
  workspace-eth-connector/src/operation.rs
  workspace-eth-connector/tests/fungible_token_tests.rs
Labels: enhancement

#28 chore: provide deploy eth-connector function
  Cargo.lock
  workspace-eth-connector/Cargo.toml
  workspace-eth-connector/src/lib.rs
  workspace-eth-connector/tests/fungible_token_tests.rs
Labels: enhancement
